### ISSUE TITLE
Find Lodash imports other than `_`

### ISSUE THREAD

**Issue by killercup** [wix/eslint-plugin-lodash#1]
In [this function](https://github.com/wix/eslint-plugin-lodash3/blob/c64e6cd1998dfeae3c7b1ea788bfae769054f410/lib/util/lodashUtil.js#L6-L8) you explicitly check for the name `_` to identify a lodash call. I try not to import lodash as `_` since I also use `_` for unused variables (many other languages to that as well).

Is it possible to extend this method to detect other names for lodash?

**Comment by ganimomer** [comment]
It should be possible. 
However, since you can't pass configuration to the whole plugin, it would have to be configured on every rule separately. That hardly seems elegant, so unless ESLint offers a different way, we won't implement this in the near future.

**Comment by killercup** [comment]
Oh, my suggestion was to actually infer the name of the lodash import from the file itself, not the configuration.

So, e.g. the `import lo from 'lodash'` or `var lo = require('lodash')` at the beginning of a file would be used to determine that every method call on `lo` should be run through this lint.

I have no idea how complex that would be, though.

**Comment by ganimomer** [comment]
We've found a technical way to resolve this issue: [the settings object](http://eslint.org/docs/user-guide/configuring#adding-shared-settings).

Reopening this issue, will close when implemented and deployed.
