### ISSUE TITLE
TypeError: transformerMethods.includes is not a function

### ISSUE THREAD

**Issue by kunagpal** [wix/eslint-plugin-lodash#109]
Node v6 adds a `.includes` for arrays, which is being used in `lib/rules/callback-binding.js:42:62`, thereby causing failed runs on Node v4,5. Has this plugin been confined to Node v6 only?

**Comment by ganimomer** [comment]
No it has not, fixed in 2.1.3.
Thanks!

**Comment by kunagpal** [comment]
:+1:
