### ISSUE TITLE
False positive for no-unbound-this

### ISSUE THREAD

**Issue by captbaritone** [wix/eslint-plugin-lodash#121]
I think "collection methods" is the wrong set of functions to associate with this rule.

Some collection methods get bound by Lodash. For example, this is valid code, but throws an error with the current implementation:

    var y = _.invokeMap(x, function () {return this.f()}):

Additionally, some non-collection methods could benefit from this rule. For example, say, `_.memoize`'s "resolver" function.

**Comment by ganimomer** [comment]
Hi,
`_.invokeMap` is not in the list of collection functions, so there's no false positive.
Opened issue #122 for the functions not covered.
