### ISSUE TITLE
rules collide

### ISSUE THREAD

**Issue by bonesoul** [wix/eslint-plugin-lodash#133]
```
_.map(juices, function (juice) {
        results.push({ type: 'juice', juice: juice });
      });
```

returns a 'collection-return' error.

when changed to 

```
_.forEach(juices, function (juice) {
        results.push({ type: 'juice', juice: juice });
      });
```

returns 'prefer-map'

These rules are colliding.

**Comment by ganimomer** [comment]
Hey,
These rules are not colliding. Both the code samples are wrong according to the plugin.
you could, for instance, use this code instead:
```js
results = results.concat(_.map(juices, function (juice) { 
  return {type: 'juice', juice: juice};
}));
```
or, if you write in ES6:
```js
results.push(..._.map(juices, juice => ({type: 'juice', juice})))
```
(The `concat` and `push` are assuming `results` had previous values. They're unnecessary if `results` is an empty array before the snippet).

**Comment by bonesoul** [comment]
okay thanks!
