### ISSUE TITLE
Add more string methods to `prefer-lodash-method` rule

### ISSUE THREAD

**Issue by skratchdot** [wix/eslint-plugin-lodash#136]
Currently, the following string methods are added to the `prefer-lodash-method` rule:
- endsWith
- includes
- padEnd
- padStart
- startsWith

A few seem to be missing:
- repeat
- replace
- split
- toLowerCase (toLower)
- toUpperCase (toUpper)
- trim
- trimStart (stage2 only?)
- trimEnd (stage2 only?)

**Comment by ganimomer** [comment]
Good point! I see you're working on a PR. Thanks!

**Comment by skratchdot** [comment]
I didn't add `trimStart` and `trimEnd` since they aren't "official" yet, but now that I think about it, if someone is using `str.trimStart()`, they should probably be using the lodash method instead.

Another thing I questioned: this rule is pretty complex at the moment.  I think it'd be nice to split things out into `prefer-endsWith`, `prefer-some`, etc, but that's a bigger / breaking change- so not sure of your thoughts on that.

Thanks for this plugin though!  I'm going to find it useful.

**Comment by ganimomer** [comment]
You're right, it is getting a bit unwieldy. But I think maybe splitting for individual methods could be too much. Maybe categories? (e.g. `prefer-lodash-collection-method`, `prefer-lodash-string-method` etc)
What do you think?

**Comment by ganimomer** [comment]
Published in `v2.3.6`.

**Comment by skratchdot** [comment]
I like that idea better I think.  At the same time, it's probably not worth the work/risk in a big refactor.  The only reason I mentioned it, is because this is the rule that caused the most errors in our codebase, so I had to disable it temporarily.  Once I fix all the errors, it won't be a big deal.

So I just threw the idea out there.  Your suggestion is definitely better than the "method-level" rules.

**Comment by skratchdot** [comment]
Thanks!!!

**Comment by ganimomer** [comment]
Okay, so I'll open an issue for it, but it means a new major version because it's a breaking change, so it'll be a while.
