### ISSUE TITLE
Create and maintain CHANGELOG.md

### ISSUE THREAD

**Issue by ganimomer** [wix/eslint-plugin-lodash#14]
Would prevent issues such as #13.

**Comment by gajus** [comment]
Just came to ask the same. Super frustrating to look into every commit (esp. since those are not squashed together) to see what has changed.

**Comment by ganimomer** [comment]
We now maintain a changelog in [CHANGELOG.md](https://github.com/wix/eslint-plugin-lodash/blob/master/CHANGELOG.md).

**Comment by mik01aj** [comment]
Great! :+1:
