### ISSUE TITLE
[Suggestion] prefer-includes also checks for .includes

### ISSUE THREAD

**Issue by leftynaut** [wix/eslint-plugin-lodash#141]
Had an issue recently where using `.includes` broke an application for Android 4.4.x users. I thought about writing a custom rule but then came across this library. Any interest in adding `.includes` along with `.indexOf`?

**Comment by ganimomer** [comment]
If you want to catch cases where you use native `includes` instead of Lodash, the rule `prefer-lodash-method` already warns for that. Or do you want to only prefer `includes` and not the other Lodash methods?

**Comment by leftynaut** [comment]
Oh - that'll work for my needs. Thank you.

**Comment by leftynaut** [comment]
Just tried this out and I get the `prefer-lodash-method` error whether I'm using a lodash method or not. Any idea what might be wrong?

Here's my .eslintrc file: http://pastebin.com/Gf7W0Bpz

**Comment by ganimomer** [comment]
That's odd. Could you give an example of code triggering this error? And how are you importing Lodash? (ES6, `require`, global, etc..?)

**Comment by leftynaut** [comment]
Via webpack with:
```
new webpack.ProvidePlugin({
    _: 'lodash',
}),
```

All four of the following lines trigger the same `prefer-lodash-method` error.
````
const test1 = _.includes([1, 2, 3], 1);
const test2 = [1, 2, 3].includes(1);
const test3 = [1, 2, 3].map((item) => { return item + item; });
const test4 = _.map([1, 2, 3], (item) => { return item + item; });
````

**Comment by ganimomer** [comment]
I see the problem. the `lodash/recommended` config tries to detect `import`s and `require`s of Lodash or its methods.
If you use `_` as a global (which you do with `webpack.ProvidePlugin`) [you should use the `lodash/canonical` config](https://github.com/wix/eslint-plugin-lodash#configuration-for-use-with-the-full-lodash-object).
That should fix it.

**Comment by leftynaut** [comment]
:)

**Comment by leftynaut** [comment]
Oh - that makes sense. My apologies for missing that in the readme.

תודה

**Comment by ganimomer** [comment]
You're welcome 😄 
Also, I updated the README to clarify that. Thanks!
