### ISSUE TITLE
Recommended configuration: Not everything should have severity 'error'

### ISSUE THREAD

**Issue by stadler** [wix/eslint-plugin-lodash#142]
Hi

The recommended/canonical configuration sets everything to severity level 'error' which is IMHO a little bit extreme.
I would find it better if all the issues in the category 'possible errors' would be errors and all others only warnings. Because 'possible errors' are a strong indication that there is a bug/error. The rules in the category 'stylistic issues' and 'preference over native' are only matters of style, and nothing that is really broken.

If would be great if this could be included into the default configuration.
If this is not possible it would be nice if there were some kind of setting that could be set to set the default severity level for this plugin.

Thanks!
   Jacques

**Comment by ganimomer** [comment]
Hi Jacques,
Thanks for opening an issue!
In my experience, working with a team of developers on the same project, anything less severe than an error gets ignored.
Also, setting recommended configs to error is pretty much standard - even `eslint:recommended` is only errors.
About a setting for severity level, ESLint doesn't give that kind of option as far as I know.

However, that's just our opinionated config. You don't have to use the config as-is. You can extend it and override some rules to warnings, or even not use it at all, and only enable specific rules.

**Comment by stadler** [comment]
Hi
Well I am used to not have any warnings/errors or if I do I either fix the issue or fix the rule. This bug report is my attempt to do the latter.
IMHO there is something wrong if warnings just get ignored. But that's an issue of how warnings are dealt with in the project.
And `eslint:recommended` has errors because those mostly really indicate that something is broken. But eslint-plugin-lodash reports many things that are just different styles of writing. And if you have to deal with older code (that did not use this plugin from the beginning), then you have suddenly 100 of errors just because of a different style. And because of a style mismatch I don't want to refactor the whole code (unless you provide auto-fixes for this).

Well, then I guess I will have to manually reduce the severity of those nearly 100 rules...

Anyway thank you for this cool plugin.
Regards, Jacques

**Comment by ganimomer** [comment]
Unfortunately, for most of the rules, the plugin doesn't have enough info about your code style to fix it correctly without possibly creating other ESLint errors. That's why most rules aren't fixable. I recommend disabling the worst offenders and then re-enabling and fixing them gradually.
