### ISSUE TITLE
False positive on callback-binding for _.findIndex, _.findLastIndex

### ISSUE THREAD

**Issue by vaskevich** [wix/eslint-plugin-lodash#147]
`_.findIndex` and `_.findLastIndex` can actually accept 3 parameters, where the last one is a start index. It seems that callback-binding reports an error when using this last parameter.

**Comment by ganimomer** [comment]
It looks like there's already a test case for what you're describing, and it works fine.
Could you give an example of code that gives a false-positive?

**Comment by vaskevich** [comment]
Weird, I do see that. I just have code like this failing, using v4 of Lodash.

    function foo(text, position) {
      const start = _.findLastIndex(text, (_c, i) => !i || /\s/.test(text[i - 1]), position);
      // ...

**Comment by ganimomer** [comment]
I couldn't reproduce the error, the code sample passed for me.
In any case, I reimplemented the rule in `v2.4.1`. Could you upgrade and check if the code still fails?

**Comment by vaskevich** [comment]
Sorry for the delay - yeah, appears to be fixed, now. Thanks for the quick turnaround!
