### ISSUE TITLE
Support for ESLint 4.0.0

### ISSUE THREAD

**Issue by kunagpal** [wix/eslint-plugin-lodash#151]
With ESLint 4.0.0, the following error comes up:
```
npm ERR! peerinvalid The package eslint@4.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-lodash@2.4.2 wants eslint@>=2.10.0
```

**Comment by ganimomer** [comment]
Hey @kunagpal, I tried installing both ESLint and the plugin in a new project, and I got no warning.
Could you please elaborate on steps to reproduce? What node and NPM version are you using?
This is especially strange, since the ESLint version actually *does* satisfy the peerDependency.

**Comment by kunagpal** [comment]
This occurs on the following:
Node v4.8.3, npm v2.15.11
Node v6.11.0, nom v3.10.10

Failed build: https://travis-ci.org/postmanlabs/postman-runtime/builds/241890399

**Comment by corbinu** [comment]
@kunagpal Can you try the build again with eslint-plugin-mocha@4.10.0 I think this may just be npm@2 giving a bad error message where eslint-plugin-lodash & eslint-plugin-jsdoc were really just warnings but eslint-plugin-mocha's range being an error caused them all to error.

**Comment by kunagpal** [comment]
@corbinu Thanks, your suggestion worked 😄
