### ISSUE TITLE
Extra (old?) files in the v2.4.3 release.

### ISSUE THREAD

**Issue by SamirTalwar** [wix/eslint-plugin-lodash#153]
This plugin has been released with two extra files: *rules/no-single-chain.js* and *rules/prefer-chain.js*. It looks like these files were removed in v2.0.0 but never deleted from the *lib* directory on the machine building it.

This isn't an issue for most users, but those of us looking at analysing ESLint-based code could choke on these two, as they're in the `rules` object exported by *index.js* but they don't load.

Could you please delete these files in the next release? (Possibly by adding an `rm` command to the build step to make sure it doesn't happen again.)

**Comment by ganimomer** [comment]
@SamirTalwar I'm not sure I understood the cases where this is problematic (I'd appreciate it if you explained), but users shouldn't have to download old files in any case, so I added a `clean` step in every build.
Fixed in `v2.4.4`.

**Comment by SamirTalwar** [comment]
Much appreciated.

More context: I'm doing a bunch of data mining on static analysis tools by throwing them at codebases to see what happens. I've started with lots of ESLint plugins, including this one. Rather than trying to configure each and every rule myself for every codebase, I'm writing software to do it for me (by effectively trying very hard). This code asks the plugin for its rules, and then tries all of them. When the rule's `create` function throws an error, my code explodes. I've written a workaround for v2.4.3 but I figured you should know anyway.

Thanks for releasing v2.4.4! Works great for me.

**Comment by ganimomer** [comment]
Sounds interesting! Thanks for taking the time to tell me about it, and for reporting in the first place.
