### ISSUE TITLE
prefer-invoke-map issue

### ISSUE THREAD

**Issue by Delagen** [wix/eslint-plugin-lodash#156]
I think
https://github.com/wix/eslint-plugin-lodash/blob/2bca90c84fe3d320e168dc854a7f236b70930416/src/rules/prefer-invoke-map.js#L21
must be written as
```
var declaredVariables = context.getDeclaredVariables(func);
```

**Comment by ganimomer** [comment]
Hi,
Thanks for taking the time to look through the code!
I need more information, though.
If the rule isn't working properly, could you give me an example of input and ESLint version that gives an unexpected result?

**Comment by Delagen** [comment]
eslint 4.4.1
