### ISSUE TITLE
Incompatible with Lodash as a global

### ISSUE THREAD

**Issue by chrisjhoughton** [wix/eslint-plugin-lodash#158]
I've started using this plugin on the server side, and one thing I've noticed recently that looks like a bug is an issue around "global" lodash.

In my Node.js app, as Lodash is used in almost every file, I've declared `global._ = _`. 

In the Eslint config, I've added Lodash to the `globals` to prevent lint errors:

```json
{
    "globals": {
        "_": false
    }
}
```

However, when I install this plugin, I start to see these lint errors from Lodash:

![image](https://user-images.githubusercontent.com/2671525/29995234-c4d1a0d2-8fdc-11e7-9720-3421334eec95.png)

![image](https://user-images.githubusercontent.com/2671525/29995236-d0876380-8fdc-11e7-9d45-0680833bbfb9.png)

It looks like the logic isn't accounting for Lodash being used as a global.

**Comment by ganimomer** [comment]
In the `recommended` configuration, the plugin looks for `import`s or `require`s of `lodash` or `lodash/<method>` to discern when you are using Lodash.
The plugin *also* has a separate configuration for using `_` as a global called [`canonical`](https://github.com/wix/eslint-plugin-lodash#configuration-for-use-with-the-full-lodash-object), which would then assume `_` is Lodash.
If you don't want to use a configuration, you can set the pragma of Lodash to `_` manually in the plugin's [shared rule settings](https://github.com/wix/eslint-plugin-lodash#shared-rule-settings).
