### ISSUE TITLE
prefer-reject warns on find

### ISSUE THREAD

**Issue by timo-lindemann-victors** [wix/eslint-plugin-lodash#162]
I get a warning on:

    const anImportantThing = find(listOfThings, function(oneThing) {
          return oneThing.isImportantBecause !== '';
    });

The rule warning me is `lodash/prefer-reject`. Is that indended?

**Comment by lindem** [comment]
to clarify: I can see why this is useful for filter(), but not for find().

**Comment by timo-lindemann-victors** [comment]
there really is no problem; upon closer inspection, it seems that my linter hung up on me. the error vanished upon restarting my ide.

sorry.
