### ISSUE TITLE
Unclear docs for `identity-shorthand`

### ISSUE THREAD

**Issue by alexilyaev** [wix/eslint-plugin-lodash#164]
The docs for this rule are noting the `max` method in regard of the identity shorthand, but `max` receives only 1 argument, so it doesn't make sense.

https://github.com/wix/eslint-plugin-lodash/blob/master/docs/rules/identity-shorthand.md

**Comment by ganimomer** [comment]
You're right. They were written before version 4 and not updated, back before it was split into `_.maxBy`.
