### ISSUE TITLE
Going to deprecate eslint-plugin-lodash, do you want the name?

### ISSUE THREAD

**Issue by mtscout6** [wix/eslint-plugin-lodash#17]
We are going to deprecate [eslint-plugin-lodash](https://github.com/eslint-plugins/eslint-plugin-lodash) in favor of your module as you have fleshed out more than we have had time to do. Seeing as lodash v4 has been released, would you guys like rights to the [eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash) name on npm?  You're already at a higher version in your project than ours so simply releasing yours will take precidence.

If you're interested I'll need to know who I should add as npm owners so you guys will have access to push to it.

**Comment by mtscout6** [comment]
Related to eslint-plugins/eslint-plugin-lodash#9

**Comment by ganimomer** [comment]
Hi,
Thanks for the offer! We'll happily take the name and go on maintaining the repo.
You can add me as an owner, my npm handle is [ganimomer](https://www.npmjs.com/~ganimomer).
Thanks!

**Comment by mtscout6** [comment]
It is done! Thanks for the great work you guys have done.

**Comment by captbaritone** [comment]
:clap:

**Comment by ganimomer** [comment]
Published eslint-plugin-lodash version 1.0.0.
Thanks!
