### ISSUE TITLE
Whitelist for "lodash/preferred-alias"

### ISSUE THREAD

**Issue by kangax** [wix/eslint-plugin-lodash#171]
It would be nice to be able to specify some sort of whitelist/exceptions for "lodash/preferred-alias".

For example, correcting `each` into `forEach` (subjectively) makes sense to me, but I'd rather use `first` instead of `head` as it's something that looks clearer to our devs unfamiliar with functional programming. 

I wouldn't want to disable this rule entirely; only certain methods.

**Comment by ganimomer** [comment]
This seems like a reasonable request.
Working on it.

**Comment by ganimomer** [comment]
Fixed in version `2.6.0`. 
[You can configure `preferred-alias` to accept an options object with an `ignoreMethods` field. ](https://github.com/wix/eslint-plugin-lodash/blob/master/docs/rules/preferred-alias.md)
Thanks for opening the issue!
