### ISSUE TITLE
Rule suggestion: Suggest sortBy if using orderBy with just `asc`

### ISSUE THREAD

**Issue by garyking** [wix/eslint-plugin-lodash#190]
Would it be a good rule idea to suggest to use `sortBy` if using `orderBy` with just `asc`?

So `_.orderBy(arr, 'text', 'asc')` would suggest to be replaced by `_.sortBy(arr, 'text')` instead, or `_.orderBy(arr, ['a', 'b'], ['asc', 'asc'])` would suggest to be replaced by `_.sortBy(arr, ['a', 'b'])` instead.

**Comment by ganimomer** [comment]
Thanks for the suggestion!
I'm not sure creating an opinionated rule here. 
Some people might prefer the opposite to be more explicit, or even to use `_.orderBy` without the second parameter, which also works. (e.g. `_.orderBy(arr, 'text')` does the exact same thing as `_.sortBy`.
In these cases, what's usually done is a rule that accepts a parameter, and the `recommended` config is opinionated.
Maybe a rule called `collection-ordering` that accepts a first parameter that's either `sortBy`, `orderBy`, or `orderByExplicit`, with the default (and the setting in the `recommended` config) being `sortBy`, and enforces that all cases are according to it.
@garyking What do you think?

**Comment by garyking** [comment]
That sounds good! The idea of using `_.orderBy` to completely replace `_.sortBy` by some people is actually interesting, and I might adopt that in my own code, since it makes it easier to change if necessary (by simply adding a third parameter to explicitly specify sort options), and to search among projects.

**Comment by ganimomer** [comment]
Fixed in `v5.0.0`.

**Comment by garyking** [comment]
Just a note, that the rule isn't listed in the readme.
