### ISSUE TITLE
Chaining is recommended, but unsure if possible

### ISSUE THREAD

**Issue by garyking** [wix/eslint-plugin-lodash#192]
`lodash/chaining` recommends chaining this code, but I'm not sure if that's possible here, or how it's done?

```js
_.isEqual(
  _.map(existing, 'name'),
  _.map(future, 'name'),
)
```

Is this the best that can be done, or can the remaining `_.map` be chained as well?

```js
_(existing)
  .map('name')
  .isEqual(_.map(future, 'name'))
```

**Comment by ganimomer** [comment]
Hi @garyking,
As far as I can tell, this is the best way it can be chained.
Can you share your config for this rule?

**Comment by garyking** [comment]
`'lodash/chaining': ['error', 'always', 2],`

**Comment by ganimomer** [comment]
In that case, yes - the way you mentioned is the way the rule expects the code to be written.
