### ISSUE TITLE
[Feature Request]: rule to prefer lodash-es over lodash or vice-versa

### ISSUE THREAD

**Issue by AndrewLeedham** [wix/eslint-plugin-lodash#204]
It would be useful to have a rule that can set a preference for `lodash` or `lodash-es`, for example:
```
// "prefers-lodash-es": ["error"] 
import { uniq } from 'lodash'; // Error
import { uniq } from 'lodash-es'; // No error
```
vs.
```
// "prefers-lodash-es": ["off"] 
import { uniq } from 'lodash'; // No error
import { uniq } from 'lodash-es'; // Error
```

Obviously if you only had one or the other installed you would get an error since one wouldn't be resolvable. But the use-case here is if you have both installed, for example we have a single codebase that powers both client-side and server-side JS, on the client we transpile lodash-es inline with Babel, whereas on the server we use normal lodash as an external dependency, we use an alias to switch between the 2, which requires all imports to be the same in the codebase, hence the rule.

**Comment by MiKolka7** [comment]
It is a standart eslint rule
```
"no-restricted-imports": [2, {
    "paths": [{
        "name": "lodash",
        "message": "Please use lodash-es instead."
    }]
}],
```

**Comment by AndrewLeedham** [comment]
Thanks @MiKolka7 was not aware of that rule. Very useful 👍
