### ISSUE TITLE
Use `~` or `^` instead of specific version

### ISSUE THREAD

**Issue by daveisfera** [wix/eslint-plugin-lodash#206]
Currently, a specific version is used (`4.17.11`) but it should use `~` or `^` so that when users update they don't have to have multiple versions installed.

**Comment by daveisfera** [comment]
A specific version is still being used. Can a `~` or `^` be used so it's not locked to a specific version?

**Comment by idok** [comment]
it's "lodash": "^4.17.15"

https://github.com/wix/eslint-plugin-lodash/blob/master/package.json#L32

**Comment by daveisfera** [comment]
Oh sorry, I just looked at the referenced PR 🤦‍♂

**Comment by idok** [comment]
no problem :)
