### ISSUE TITLE
Add rule: identity-shorthand

### ISSUE THREAD

**Issue by captbaritone** [wix/eslint-plugin-lodash#24]
I've added this rule in my Underscore fork, and I think it would fit here as well. It completes the set of _.iteratee shorthands.

Would you like me to open a PR?

https://github.com/captbaritone/eslint-plugin-underscore/blob/master/docs/rules/identity-shorthand.md

**Comment by ganimomer** [comment]
Looks great.
We would, thanks!

**Comment by ganimomer** [comment]
implemented by @captbaritone in version 1.1.0
