### ISSUE TITLE
Rule idea: superfluous arguments passed to _.uniq

### ISSUE THREAD

**Issue by captbaritone** [wix/eslint-plugin-lodash#26]
Seems like this could be a common migration error. I'm not that up on Lodash, but it looks like there may be other methods that have gone through a similar transformation.

https://github.com/lodash/lodash/issues/2006

**Comment by ganimomer** [comment]
Sounds simple enough. We'll go ahead and implement it unless anyone wants to contribute.

**Comment by mik01aj** [comment]
@ganimomer I see you implemented the rule for all of lodash, good job! :+1:

**Comment by ganimomer** [comment]
It seemed silly to only implement it for `_.uniq`. Thanks!

**Comment by captbaritone** [comment]
:clap: :clap:

**Comment by jdalton** [comment]
Wow! This is fantastic!
