### ISSUE TITLE
Version 7.1.0 is failing on the project with Lodash v3

### ISSUE THREAD

**Issue by vicneanschi** [wix/eslint-plugin-lodash#266]
I'm getting this error when trying to use this plugin on the project with Lodash 3

```
ESLint: 7.5.0

TypeError: Failed to load plugin 'lodash' declared in '.eslintrc.js': _.overSome is not a function
```
I saw the with the fix https://github.com/wix/eslint-plugin-lodash/pull/255 already made it to master.

Would it be possible to release new version with this fix?

**Comment by idok** [comment]
published
