### ISSUE TITLE
Coveralls badge link is broken

### ISSUE THREAD

**Issue by captbaritone** [wix/eslint-plugin-lodash#34]
<img width="930" alt="screen shot 2016-03-01 at 10 42 58 am" src="https://cloud.githubusercontent.com/assets/162735/13437702/6dfdcd7e-df9a-11e5-8f90-23c64cd0a1af.png">

**Comment by ganimomer** [comment]
That's why the badge says 'coverage:unknown' (when it should say 100% :smile:)
We're working internally on fixing it, and then the badge (and link) will work properly.
Thanks!

**Comment by ganimomer** [comment]
I've removed the badge until we manage to resolve this issue.
We'll return it when we can.
