### ISSUE TITLE
Add option to remove specific methods from prefer-lodash-method

### ISSUE THREAD

**Issue by corbinu** [wix/eslint-plugin-lodash#38]
It would be better if prefer-lodash-method had the ability to allow a certain method to not be preferred. In my case "_.find" is falsely triggering on non arrays with find (For example the find method of http://mongoosejs.com/docs/index.html)

It would be nice to be able to set something like
```
"lodash/prefer-lodash-method": [2, {"find": false}]
```

Is a great project really love it thanks for your time!

**Comment by ganimomer** [comment]
Hi,
Thanks for taking the time for feedback! This looks like it would improve the rule, we'll add it next version.

**Comment by corbinu** [comment]
Sounds great thanks!
