### ISSUE TITLE
Add extendable set of recommended rules

### ISSUE THREAD

**Issue by alexlrobertson** [wix/eslint-plugin-lodash#40]
It would be helpful to have a set of recommended rules that one could easily add to your [rule extensions](http://eslint.org/docs/user-guide/configuring#extending-configuration-files). There should likely be two sets: one for version 3 rules and one for version 4 rules.

See [Airbnb’s Eslint config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) for an example.

**Comment by ganimomer** [comment]
Good idea, we'll work on it.

**Comment by ganimomer** [comment]
Added in `1.4.0`.
