### ISSUE TITLE
prefer-includes misses a few cases

### ISSUE THREAD

**Issue by captbaritone** [wix/eslint-plugin-lodash#53]
I'll include some examples from our code base:

```
if (!str || _.indexOf(str, "_") < 0) {

if (_.indexOf(self.unmatchedColumns, idx) > -1) {

if (_.indexOf(recommendedNetworks, network.get('network')) >= 0) {
```
There are theoretically lots of other ways this could be written, but I'm sure there is a point of diminishing returns. Here is the rough draft I came up with which tries to be very clever about finding all kinds of edge cases:

captbaritone@c2059a8

It's pretty gross and I don't like it at all, which is why I still haven't merged it. I'm guessing something less "clever" (like your solution) but that catches the above three cases would be a nice middle-ground.

**Comment by ganimomer** [comment]
Hi,
Sorry for not responding to this on the original thread.
I agree with you about the middle ground. I'll see if I can find an elegant way to add it, or you're welcome to submit a PR.

**Comment by captbaritone** [comment]
I'd love to see what you come up with ;)

--
Jordan Eldredge

Please excuse any typos or terseness; this email was sent from a mobile device.
