### ISSUE TITLE
path-style recommended setting

### ISSUE THREAD

**Issue by loris** [wix/eslint-plugin-lodash#58]
@jdalton ran a [twitter poll about preferred path style](https://twitter.com/jdalton/status/718165294678552576), and it looks like `string` was a clear winner over `array`. Was wondering if it would make more sense to change the setting in the `recommended` configuration?

**Comment by ganimomer** [comment]
Like it says in the [docs for `path-style`](https://github.com/wix/eslint-plugin-lodash/blob/master/docs/rules/path-style.md), there's reasoning in our choice for the default value and the `recommended` configuration - It's faster.
The rule itself was built to not be opinionated and allow enforcing both styles, but the `recommended` config reflects our opinions.
Anyone who prefers using strings can override it in their own project config.

**Comment by jdalton** [comment]
Lodash has since memoized the string patch giving it a [significant perf boost](http://jsperf.com/get-vs-get-cache#chart=table). Now both paths are over a million operations per second which makes it a non-issue for most now.

**Comment by captbaritone** [comment]
If you are going to enforce one consistent style, the array style might still be the one to enforce (independent of perf) since there are some edge cases which can only be expressed using the array syntax.

Either way, I don't think it's worth fretting over the recommended values too much since folks can easily configure the plugin in a way that works best for them.

**Comment by jdalton** [comment]
@captbaritone It's not enforcing a consistent style. The default rule is `as-needed` which means it juggles between strings for single property paths and arrays for deep. I think it'd be easier to avoid juggling and settle on the string path. If folks want the array path (or are concerned with edge cases) then its configurable for that.

**Comment by mik01aj** [comment]
>I don't think it's worth fretting over the recommended values too much since folks can easily configure the plugin in a way that works best for them.

@captbaritone, I disagree. With good defaults we can make this plugin work great out of the box (like mac). When users have to go through all the configs manually, it's do-it-yourself and thus less friendly (like linux).

**Comment by ganimomer** [comment]
You've made valid points. Reopening the issue and fixing.

**Comment by ganimomer** [comment]
Changed in `v1.6.5`.
