### ISSUE TITLE
lodash/path-style

### ISSUE THREAD

**Issue by Delagen** [wix/eslint-plugin-lodash#61]
Do not require string  for single level depths when path is variable

Example:
```
var field="aaa";
_.get(obj,[field])
```

**Comment by ganimomer** [comment]
Hi,
Could you give a bit more details?
What's the rule's config? What error message are you getting?

Thanks

**Comment by Delagen** [comment]
"lodash/path-style":              [2, "as-needed"],

**Comment by ganimomer** [comment]
Why not?
The only guess I have is that you're using an array to make sure this only goes one level if the variable happens to have `.` in it? It would still work, and would take precedence over parsing it as a deep path.

```js
const a = {b: {c: 'd'}}
const field = 'b.c'
a[field] = 'e'
console.log(_.get(a, field)) // => e
```

Could you explain your reasoning a bit more please?

**Comment by ganimomer** [comment]
Closing the issue since it is unclear what is required.
