### ISSUE TITLE
prefer-lodash-method false positive on slice string

### ISSUE THREAD

**Issue by corbinu** [wix/eslint-plugin-lodash#63]
prefer-lodash-method creates a false positive on slicing a string. `_.slice` does not behave the same as `string.slice`

If I am incorrect please let me know but I am pretty sure that string.slice is less then `_.slice_.toArray(string))`

**Comment by ganimomer** [comment]
Looks like you're right. Like all collection methods in Lodash, `_.slice` returns an array, while `String.Prototype.slice` returns a string.
Fixing.

**Comment by corbinu** [comment]
Thanks!
