### ISSUE TITLE
callback-binding error on _.zipWith

### ISSUE THREAD

**Issue by adi-mor** [wix/eslint-plugin-lodash#64]
Hi,

Thanks for this plugin, we want to use it but encountered several issues as the following,

This sample code from [_.zipWith lodash docs](http://devdocs.io/lodash~4/index#zipWith):
```
_.zipWith([1, 2], [10, 20], [100, 200], function(a, b, c) {
  return a + b + c;
});
```

Reports an error:

> Do not use Lodash 3 thisArg, use binding instead (lodash/callback-binding)

Seems to be a problem with analyzing the (…Array) argument

**Comment by ganimomer** [comment]
On it. If there are other issues, please report them and we'll make sure to fix them.

**Comment by adi-mor** [comment]
Thanks for the quick fix!

**Comment by faiwer** [comment]
Equal situation with `sortedIndexBy`:
```js
let idx = _.sortedIndexBy(collection, value, 'property');
// Do not use Lodash 3 thisArg, use binding instead (lodash/callback-binding)
```
in docs: `_.sortedIndexBy(array, value, [iteratee=_.identity])`

**Comment by ganimomer** [comment]
Fixed the bug with `_.sortedIndexBy` in v1.8.4.
Thanks for the heads up!
