### ISSUE TITLE
no-extra-args error on _.attempt

### ISSUE THREAD

**Issue by adi-mor** [wix/eslint-plugin-lodash#65]
Hi,

Here is another issue,

This sample code from [_.attempt lodash docs](http://devdocs.io/lodash~4/index#attempt):
`var elements = _.attempt(function(selector) {
  return document.querySelectorAll(selector);
}, '>_>');`

Reports:

> Too many arguments passed to `attempt` (expected 1)  (lodash/no-extra-args)

Again seems to be a problem with analyzing an argument of type (…*)

**Comment by ganimomer** [comment]
Looks like it.
Since there's no single-source-of-truth about the number of arguments a Lodash function gets, there was bound to be a mistake.
On it.

**Comment by adi-mor** [comment]
Thank you
