### ISSUE TITLE
Make `prefer-constant` work for function declarations

### ISSUE THREAD

**Issue by jfmengels** [wix/eslint-plugin-lodash#70]
I noticed that `prefer-constant` did not lint for function declarations. Currently, the following passes:

```js
function three() {
  return 3;
}
```
while the following lints an error.
```js
var three = function() {
  return 3;
};
```

If this is by design, I'd be interested to know the reason. If not, I'm willing to make a PR amending it.

**Comment by ganimomer** [comment]
The intent of the rule is to replace anonymous functions, like ones used for callbacks.
Assigning a function to a variable is a bit semantically different from creating a named function. 
For instance, one is hoisted and one isn't, so replacing this:
```js
var six = three() * 2
function three() {
  return 3;
}
```
with this:
```var six = three() * 2
var three = function() { 
  return 3;
}
Would result in a `TypeError`. The same error would occur if we replaced it with `_.constant`, and if we used `const` or `let` instead of `var` it would be a `ReferenceError` because of temporal dead zones.

Despite that, I think we could add a second boolean rule option, `includeDeclarations`, for people who would use it responsibly. Would you like to submit a PR?

**Comment by jfmengels** [comment]
Hmm. I just ported the same rule to https://github.com/jfmengels/eslint-plugin-lodash-fp and included the function declaration case. I haven't published the version with it yet though, so I was curious as to the reason.

There is indeed a difference in both declaration styles (regarding hoisting as you said), but to me (and in the wording of the docs), it's not about anonymous function, but either about having a consistent style for this behavior, or about conciseness (which explains why activating it for arrow functions is behind a flag, because they're shorter than `_.constant()`).

To me, the error you described is more a case for enforcing [no-use-before-define](http://eslint.org/docs/rules/no-use-before-define) (though it's not exactly the same, I agree).

I think I'll keep the current behavior in my `fp` repo, but in the case of this repo, adding it would probably be more of a breaking change, so adding it behind a flag would probably be a more reasonable choice. I'm willing to submit a PR, I'll see when I have time (though my thoughts are more on working on the fp repo :D)

**Comment by ganimomer** [comment]
Good, we're in agreement.
It's just that I don't want that fixing any of the plugin's rules would introduce errors, and I don't think any rule should make assumptions about any of the other rules being on. (For instance, in the original codebase this plugin was developed for, `no-use-before-define` is not always on).

I can get to it myself, if you prefer.

**Comment by jfmengels** [comment]
> I don't want that fixing any of the plugin's rules would introduce errors

:+1:. Might be worth considering when releasing the next major release, but this alone is not worth a breaking change. 

> I can get to it myself, if you prefer.

Starting to work on it now ;)
