### ISSUE TITLE
Feature Request: Detect likely bugs when using `lodash-webpack-plugin`

### ISSUE THREAD

**Issue by ryan-roemer** [wix/eslint-plugin-lodash#97]
The [`lodash-webpack-plugin`](https://github.com/lodash/lodash-webpack-plugin) is great for honing down lodash includes in ultimate production bundles. But getting a handle on which [feature sets](https://github.com/lodash/lodash-webpack-plugin#feature-sets) you need to one-off set to `true` to keep your code functioning correctly has been a bit of challenge across our open source and client work -- we've had numerous bugs that we tracked down to not fully understanding which feature set flags need toggles for our usage. (See, e.g. https://github.com/FormidableLabs/builder-victory-component/pull/74)

**Feature Request**: It would be fantastic if this plugin could somehow detect potential improper feature set settings for _actual code usage_ and output warnings like: "You've got what seems to be a deep path in `_.set()` usage, but don't have `paths: true` set!"

There's a slight complication in that the relevant webpack config would need to be read to see what feature flags are already set (or manually duplicating those in this plugin's settings).

But I think if we could get some automagic guidance to proper `lodash-webpack-plugin` usage, that would be huge for furthering adoption / minimzing frustration with an otherwise wonderful webpack plugin!

**Super Extra Special Feature Request**: If the above is possible, then doing the opposite check to detect and identify feature sets that are set to `true` but aren't actually needed would be great for allowing dev's to them slim down their builds even further...

/cc @jdalton

**Comment by ganimomer** [comment]
Hi,
While I can see that this would be helpful to some people, this seems like too specific a use case for including in this plugin.
There are several ways to use Lodash nowadays, and while we're currently working on the use case of specific method imports (which Lodash itself enables), a plugin that's specific for Webpack is not a 'standard' way, so I don't think it should be in this plugin.
You're more than welcome to fork or otherwise use the infrastructure in this plugin to support a different plugin specifically for this purpose.

**Comment by ryan-roemer** [comment]
@ganimomer -- That's too bad. And my intuition is the Lodash core folks do indeed hope that `lodash/lodash-webpack-plugin` becomes the "standard" way for Lodash to be integrated in webpack-based applications and libraries.

@jdalton -- Unfortunately, looks like your first suggestion is a bust. Any other ideas for landing this helper with a project / community that might be more appropriate? Thanks!

**Comment by jdalton** [comment]
@ryan-roemer We'll see if someone starts a `eslint-plugin-lodash-webpack`. Folks using `lodash-webpack-plugin` on an established project should probably start with everything enabled and then turn the features off one by one and refactor as needed. Folks using `lodash-webpack-plugin` on a new project should go with the defaults (feature sets turned off) until they hit a feature they need.
